EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
  SpaceAroundErbTag:
    enabled: true
  HardCodedString:
    enabled: false
  FinalNewline:
    enabled: true
  Indentation:
    enabled: true
    character: space
    width: 2
  ClosingErbTagIndentation:
    enabled: true
exclude:
  - 'vendor/**/*'
