FROM ruby:3.2.2
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y ca-certificates curl gnupg && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

# Node.jsとその他の依存関係のインストール
RUN apt-get update -qq && \
    apt-get install -y nodejs build-essential libpq-dev vim postgresql-client

# Yarnのインストール
RUN npm install -g yarn

# 作業ディレクトリの設定
WORKDIR /parts_sync

# GemfileとGemfile.lockをコピー
COPY Gemfile Gemfile.lock ./

# bundle installの実行
RUN bundle install

# Yarnの初期化とパッケージのインストール
RUN yarn install
