services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parts_sync_development
      TZ: Asia/Tokyo
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/parts_sync_development
      BUNDLE_PATH: /usr/local/bundle
      TZ: Asia/Tokyo
    volumes:
      - .:/parts_sync:cached
      - bundle_data:/usr/local/bundle
      - node_modules:/parts_sync/node_modules
      - tmp-data:/parts_sync/tmp
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true

volumes:
  postgresql_data:
  bundle_data:
  node_modules:
  tmp-data:
