name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]  # mainブランチへのプッシュをトリガーにする
  pull_request:
    branches: [ "main" ]  # mainブランチへのプルリクエストをトリガーにする
jobs:
  test:
    runs-on: ubuntu-latest  # テストジョブは最新のUbuntuで実行
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # コードをチェックアウトするアクションを使用

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Docker Buildxをセットアップするアクションを使用

      - name: Build and run tests
        run: |
          # Dockerコンテナをビルド
          docker-compose build
          docker-compose run --rm web bash -c "
            # 必要なGemをインストール
            bundle install && \
            # データベースを作成し、スキーマをロード
            bin/rails db:create db:schema:load && \
            # Railsのテストを実行
            bundle exec rails test && \
            # システムテストを実行
            bundle exec rails test:system
          "

  lint:
    runs-on: ubuntu-latest  # リントジョブも最新のUbuntuで実行
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # コードをチェックアウトするアクションを使用

      - name: Build and run linters
        run: |
          # Dockerコンテナをビルド
          docker-compose build
          docker-compose run --rm web bash -c "
            # 必要なGemをインストール
            bundle install && \
            # Linter用のバイナリを生成
            bundle binstubs bundler-audit brakeman rubocop && \
            # bundler-auditで脆弱性をチェック
            bin/bundler-audit --update && \
            # brakemanでセキュリティチェック
            bin/brakeman -q -w2 && \
            # rubocopでコードスタイルをチェック
            bin/rubocop --parallel
          "
